const express = require('express')
const router = express.Router()
const { getHomepage, PostLoginUser, RouterToken, LogoutToken, CreareClient, CreateUser } = require('../controllers/homecontroller')
const { CreateBooks, UpdateBook, deleteBook, UpdateTitleBook, UpdateSummerybook, UpdateBookCategory, UpdateWriteBook, bookList } = require('../controllers/book')
const verifyToken = require('../auth')
const { CreateReservation, deleteReservation, UpdateReservation } = require('../controllers/reservation')
//const { mongodata } = require('../mongodata')
const { PostLoginUser1, RouterToken1, LogoutToken1 } = require('../loginusemongodata')
const verifyToken1 = require('../middleware')
const { CreateClient1, CreateUser1 } = require('../createUsermongo')
const { CreateBooks1, UpdateBook1, deleteBook1 } = require('../SetBook')
const { CreateReservation1, UpdateReservation1, deleteReservation1 } = require('../SetReservation')
router.get('/', getHomepage)
router.post('/login', PostLoginUser)
router.get('/role', verifyToken, (req, res) => {
    res.json(res.locals.user)
})
router.post('/token', RouterToken)
router.delete('/logout', verifyToken, LogoutToken)
router.post('/create1', CreareClient)
router.post('/create2', verifyToken, CreateUser)
router.post('/createbook', verifyToken, CreateBooks)
router.post('/updatebook', verifyToken, UpdateBook)
router.post('/delete', verifyToken, deleteBook)
router.post('/createreservation', verifyToken, CreateReservation)
router.post('/updateReservation', verifyToken, UpdateReservation)
router.post('/deletereservation', verifyToken, deleteReservation)
router.get('/bookList', bookList)
router.post('/login1', PostLoginUser1)
router.post('/token1', RouterToken1)
router.get('/user', verifyToken1, (req, res) => { res.json(res.locals.users) })
router.post('/logout1', verifyToken1, LogoutToken1)
router.post('/createclient1', CreateClient1)
router.post('/createuser1', verifyToken1, CreateUser1)
router.post('/createbook1', verifyToken1, CreateBooks1)
router.post('/updatebook1', verifyToken1, UpdateBook1)
router.post('/deletebook1', verifyToken1, deleteBook1)
router.post('/createreservation1', verifyToken1, CreateReservation1)
router.post('/updatereservation1', verifyToken1, UpdateReservation1)
router.post('/deletereservation1', verifyToken1, deleteReservation1)
module.exports = router